obj-$(CONFIG_PWM_IMX6)             += pwm_generic.o pwm_seco.o
obj-$(CONFIG_ECONTROLLER)          += econtroller.o
obj-$(CONFIG_RTC_DRV_BRIDGE)       += rtc-bridge.o
obj-$(CONFIG_MACH_MX6_SECO_Q7)     += cpld.o
obj-$(CONFIG_SECO_GPIO_EXPANDER)   += gpio_expander.o
obj-$(CONFIG_SECO_W83627DHG_LPC)   += w83627dhg.o w83627dhg_gpio2.o w83627dhg_gpio3.o lpc.o lpc_table.o
obj-$(CONFIG_SECO_XR28V382_LPC)    += xr28v382.o lpc.o lpc_table.o
obj-$(CONFIG_MACH_MX6_SECO_A62)	   += pwrbutton_management.o
